
const AboutPage = () => {
  return (
    <div className="about-page">
      <h1>About Page</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor fuga possimus est molestias quam accusantium impedit illum doloribus, rem perspiciatis eveniet omnis quia culpa provident saepe, eos animi corporis at aliquid natus consectetur dicta quibusdam repudiandae vitae! Iure impedit ipsa debitis magnam quasi voluptatibus quis est a asperiores deleniti quaerat qui obcaecati et unde pariatur optio ipsum quia temporibus, nam minima, fugiat expedita autem dolores. Veniam tempora officia quisquam maxime!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor fuga possimus est molestias quam accusantium impedit illum doloribus, rem perspiciatis eveniet omnis quia culpa provident saepe, eos animi corporis at aliquid natus consectetur dicta quibusdam repudiandae vitae! Iure impedit ipsa debitis magnam quasi voluptatibus quis est a asperiores deleniti quaerat qui obcaecati et unde pariatur optio ipsum quia temporibus, nam minima, fugiat expedita autem dolores. Veniam tempora officia quisquam maxime!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor fuga possimus est molestias quam accusantium impedit illum doloribus, rem perspiciatis eveniet omnis quia culpa provident saepe, eos animi corporis at aliquid natus consectetur dicta quibusdam repudiandae vitae! Iure impedit ipsa debitis magnam quasi voluptatibus quis est a asperiores deleniti quaerat qui obcaecati et unde pariatur optio ipsum quia temporibus, nam minima, fugiat expedita autem dolores. Veniam tempora officia quisquam maxime!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor fuga possimus est molestias quam accusantium impedit illum doloribus, rem perspiciatis eveniet omnis quia culpa provident saepe, eos animi corporis at aliquid natus consectetur dicta quibusdam repudiandae vitae! Iure impedit ipsa debitis magnam quasi voluptatibus quis est a asperiores deleniti quaerat qui obcaecati et unde pariatur optio ipsum quia temporibus, nam minima, fugiat expedita autem dolores. Veniam tempora officia quisquam maxime!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor fuga possimus est molestias quam accusantium impedit illum doloribus, rem perspiciatis eveniet omnis quia culpa provident saepe, eos animi corporis at aliquid natus consectetur dicta quibusdam repudiandae vitae! Iure impedit ipsa debitis magnam quasi voluptatibus quis est a asperiores deleniti quaerat qui obcaecati et unde pariatur optio ipsum quia temporibus, nam minima, fugiat expedita autem dolores. Veniam tempora officia quisquam maxime!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor fuga possimus est molestias quam accusantium impedit illum doloribus, rem perspiciatis eveniet omnis quia culpa provident saepe, eos animi corporis at aliquid natus consectetur dicta quibusdam repudiandae vitae! Iure impedit ipsa debitis magnam quasi voluptatibus quis est a asperiores deleniti quaerat qui obcaecati et unde pariatur optio ipsum quia temporibus, nam minima, fugiat expedita autem dolores. Veniam tempora officia quisquam maxime!</p>
    </div>
  );
};

export default AboutPage;
